package org.howard.edu.lsp.finalexam.question2;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

public class RandomNumberClientTest {

    @Test
    void testBuiltInRandomNumberStrategy() {
        RandomNumberService service = RandomNumberService.getInstance();

        // Set the generator to BuiltInRandomNumberStrategy
        service.setGenerator(new BuiltInRandomNumberStrategy());

        // Generate a random number and check that it is positive
        int randomNumber = service.getRandomNumber();
        assertTrue(randomNumber > 0, "Random number generated by BuiltInRandomNumberStrategy should be positive");
    }

    @Test
    void testCustomRandomNumberGenerator() {
        RandomNumberService service = RandomNumberService.getInstance();

        // Set the generator to CustomRandomNumberGenerator
        service.setGenerator(new CustomRandomNumberGenerator());

        // Generate a random number and check that it is positive
        int randomNumber = service.getRandomNumber();
        assertTrue(randomNumber > 0, "Random number generated by CustomRandomNumberGenerator should be positive");
    }

    @Test
    void testSingletonInstance() {
        // Ensure RandomNumberService is a singleton
        RandomNumberService instance1 = RandomNumberService.getInstance();
        RandomNumberService instance2 = RandomNumberService.getInstance();
        assertSame(instance1, instance2, "RandomNumberService should always return the same instance");
    }
}
